### ISSUE TITLE
Settle on Pulumi Language

### ISSUE THREAD

**Issue by rawkode** [tinkerbell/infrastructure#3]
When I initially wrote the Pulumi automation, I used TypeScript. This language seems to be well suited to IaaC, because it is strictly typed and tries to keep boilerplate to a minimum, such as explict error handling, concise syntax for anonymous functions, and better control of imports and exports across modules.

However, the Tinkerbell team doesn't have much experience in TypeScript and we opted to use a more familiar language: Go.

I think there's definitely value in moving back to TypeScript before we get too deep into this project, but as the initial migration to Go is also complete - I don't wanna take any decision for granted. Maybe our future use-cases aren't too vast and we've already got what we need.

Leaving this open for discussion with @gianarb @thebsdbox @benr

**Comment by tstromberg** [comment]
@rawkode - any further thoughts on this topic?

I personally don't care either way what language the infrastructure is defined in, so long as it's low in cognitive complexity.

**Comment by rawkode** [comment]
What we have in Go works and the team are familiar with Go. Happy to close.
