### ISSUE TITLE
Remove GitHub Action Runner as Root

### ISSUE THREAD

**Issue by rawkode** [tinkerbell/infrastructure#5]
I'm assuming, for now, that we need this to run as root for our tests; as we'll be launching VMs and other weird stuff.

https://github.com/tinkerbell/infrastructure/commit/ddf97a9b6e4a380b24f1c0edb03e16860bf11954

@gianarb can you let me know if this is incorrect?

**Comment by gianarb** [comment]
```
root@gh-runner-test:~# ps aux | grep runner
runner   1716496  0.0  0.0   6892  3312 ?        Ss   Feb09   0:00 /bin/bash /home/runner/actions-runner/runsvc.sh
runner   1716507  0.0  0.0 550912 29228 ?        Sl   Feb09   0:00 ./externals/node12/bin/node ./bin/RunnerService.js
runner   2409590  0.0  0.1 3474676 116132 ?      Sl   Feb11   0:06 /home/runner/actions-runner/bin/Runner.Listener run --startuptype service
```

It can run as non-root!! (that's the runner we are using now)

Thanks @rawkode !
