### ISSUE TITLE
Enable a place where we can deploy static assets such as hook releases

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/infrastructure#8]
## Expected Behaviour

We need a place where we can store and deploy static assets such as operating systems:

1. we need to push hook releases somewhere.
2. @thebsdbox worked at extending https://github.com/kubernetes-sigs/image-builder to release images that CAPT can use, it will be great to release them there as well.
3. Who knows what

At some point, it will be nice to aggregate stats to figure out usage.

## Current Behaviour

OSIE has its own S3 bucket. I would like to get something properly branded with a CNAME and so on.

OSIE will keep its own way btw.

## Possible Solution

An S3 bucket with a CNAME to assets.tinkerbell.org or maybe better to releases.tinkerbell.org

**Comment by gianarb** [comment]
If possible I would like to get credentials sets to tinkerbell/hook repository to be able to push files to the `./hook` subdirectory. Thansk!

**Comment by mmlb** [comment]
Well the current buckets are tinkerbell-oss and tinkerbell-oss-pr, not tied to OSIE specifically. We could get a new set of `tinkerbell` and `tinkerbell-pr` buckets too.

Feel free to ignore OSIE, we're starting to try out hook and will be dropping ASAP :D.

**Comment by rawkode** [comment]
I believe this has been sorted. Please reopen if I've forgotten anything.
